import JSZip from 'jszip';
import { AIButtonStudioComponent, DesignTokens } from '../types';

/**
 * Generates automated header attribution watermark per Section 1.5
 */
function getAttributionHeader(attribution: AIButtonStudioComponent['attribution']): string {
  return `/**
 * ============================================================================
 * AI Button Studio - Auto-Credit & Ethical Attribution Registry
 * Author / Credit: ${attribution.credit_owner}
 * License: ${attribution.license_type}
 * Source Repository: ${attribution.source_repository || 'https://github.com/mutiagent-base/ai-button-studio-app-design'}
 * Generated by AI Button Studio Compiler
 * ============================================================================
 */\n\n`;
}

/**
 * Generates a consolidated attribution header for multi-component bundles
 */
function getMultiAttributionHeader(components: AIButtonStudioComponent[]): string {
  const credits = Array.from(new Set(components.map(c => c.attribution.credit_owner))).join(', ');
  const licenses = Array.from(new Set(components.map(c => c.attribution.license_type))).join(', ');
  const dateStr = new Date().toISOString();

  return `/**
 * ============================================================================
 * AI Button Studio - Multi-Component Bundle & Ethical Attribution
 * Bundled Items: ${components.length} components (${components.map(c => c.content.label).join(', ')})
 * Authors / Credits: ${credits || 'AI Button Studio Community'}
 * Licenses: ${licenses || 'MIT'}
 * Generated at: ${dateStr}
 * Source Repository: https://github.com/mutiagent-base/ai-button-studio-app-design
 * ============================================================================
 */\n\n`;
}

export function generateReactCode(component: AIButtonStudioComponent, tokens: DesignTokens): string {
  const isRGB = component.effects.special_features.includes('rgb_running_border');
  const isDynamicShadow = component.effects.special_features.includes('dynamic_shadow_cursor_tracking');

  return `${getAttributionHeader(component.attribution)}import React, { useState, useRef, useEffect } from 'react';
import { Sparkles, Rocket, Search, Plus, ArrowRight, Check, Loader2 } from 'lucide-react';

export interface LivingButtonProps {
  onClick?: () => void;
  disabled?: boolean;
  className?: string;
}

export const ${toPascalCase(component.content.label || 'LivingButton')}: React.FC<LivingButtonProps> = ({
  onClick,
  disabled = false,
  className = '',
}) => {
  const [state, setState] = useState<'idle' | 'hover' | 'loading' | 'success' | 'error'>('idle');
  const buttonRef = useRef<HTMLButtonElement>(null);

  ${isDynamicShadow ? `// 1. Dynamic Cursor Proximity Shadow Tracking (Section 3.3.A)
  useEffect(() => {
    const btn = buttonRef.current;
    if (!btn || disabled || state === 'loading') return;

    const handleMouseMove = (event: MouseEvent) => {
      const bounds = btn.getBoundingClientRect();
      const centerX = bounds.left + bounds.width / 2;
      const centerY = bounds.top + bounds.height / 2;

      const diffX = event.clientX - centerX;
      const diffY = event.clientY - centerY;

      // Dampen projection factor
      const shadowOffsetX = -(diffX / 16);
      const shadowOffsetY = -(diffY / 16);

      const distance = Math.sqrt(diffX * diffX + diffY * diffY);
      const blurRadius = Math.min(28, Math.max(8, 3500 / (distance + 1)));

      btn.style.boxShadow = \`\${shadowOffsetX.toFixed(1)}px \${shadowOffsetY.toFixed(1)}px \${blurRadius.toFixed(1)}px rgba(0, 0, 0, ${tokens.shadowIntensity})\`;
    };

    const handleMouseLeave = () => {
      btn.style.boxShadow = '';
    };

    window.addEventListener('mousemove', handleMouseMove);
    btn.addEventListener('mouseleave', handleMouseLeave);
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      btn.removeEventListener('mouseleave', handleMouseLeave);
    };
  }, [disabled, state]);` : ''}

  const handleClick = async (e: React.MouseEvent<HTMLButtonElement>) => {
    if (disabled || state === 'loading') return;
    setState('loading');

    try {
      if (onClick) await onClick();
      setState('success');
      setTimeout(() => setState('idle'), 1500);
    } catch {
      setState('error');
      setTimeout(() => setState('idle'), 1200);
    }
  };

  return (
    <button
      ref={buttonRef}
      id="${component.id}"
      type="button"
      tabIndex={${component.accessibility.tab_index}}
      aria-label="${component.accessibility.aria_label}"
      disabled={disabled || state === 'loading'}
      onClick={handleClick}
      onMouseEnter={() => setState('hover')}
      onMouseLeave={() => state !== 'loading' && state !== 'success' && setState('idle')}
      className={\`group relative inline-flex items-center justify-center gap-2.5 px-6 py-3 text-sm font-semibold tracking-wide transition-all duration-200 outline-none
        ${isRGB ? 'living-btn-rgb' : getBaseStyleClasses(component.effects.base_style)}
        \${state === 'loading' ? 'cursor-wait opacity-85' : 'cursor-pointer'}
        \${state === 'error' ? 'animate-shake !bg-rose-600 !text-white' : ''}
        \${state === 'success' ? 'animate-success-pop !bg-emerald-600 !text-white' : ''}
        \${disabled ? 'opacity-40 cursor-not-allowed filter grayscale' : 'hover:scale-[1.02] active:scale-[0.98]'}
        \${className}\`}
      style={{
        borderRadius: '${tokens.borderRadius === 9999 ? '9999px' : `${tokens.borderRadius}px`}',
        ['--btn-transition-timing' as any]: '${tokens.transitionTiming}',
        transitionTimingFunction: '${tokens.transitionTiming}',
      }}
    >
      {state === 'loading' ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin text-cyan-300" />
          <span>Processing...</span>
        </>
      ) : state === 'success' ? (
        <>
          <Check className="w-4 h-4 text-white" />
          <span>Completed</span>
        </>
      ) : (
        <>
          ${renderIconJSX(component.content.icon_name)}
          <span>${component.content.label}</span>
        </>
      )}
    </button>
  );
};
`;
}

/**
 * Generates a bundled JSON representation of multiple selected button IRs
 */
export function generateBundledJson(
  components: AIButtonStudioComponent[],
  tokens: DesignTokens,
  bundleTitle: string = 'AI Button Studio Export'
): string {
  const bundle = {
    schema_version: '2.4.0',
    bundle_name: bundleTitle,
    exported_at: new Date().toISOString(),
    total_components: components.length,
    design_tokens: tokens,
    components: components,
  };

  return JSON.stringify(bundle, null, 2);
}

/**
 * Generates a single bundled React TSX file containing all selected button components
 */
export function generateBundledReactCode(
  components: AIButtonStudioComponent[],
  tokens: DesignTokens,
  bundleTitle: string = 'ButtonBundle'
): string {
  if (components.length === 0) {
    return `// No components selected for export. Please select at least one button.`;
  }

  // Collect unique icon names needed across all buttons
  const iconSet = new Set<string>(['Check', 'Loader2']);
  components.forEach(c => {
    const iconName = c.content.icon_name;
    if (iconName === 'rocket') iconSet.add('Rocket');
    else if (iconName === 'sparkles') iconSet.add('Sparkles');
    else if (iconName === 'search') iconSet.add('Search');
    else if (iconName === 'plus') iconSet.add('Plus');
    else if (iconName === 'arrow-right') iconSet.add('ArrowRight');
    else if (iconName === 'check') iconSet.add('Check');
    else if (iconName === 'play') iconSet.add('Play');
    else if (iconName === 'download') iconSet.add('Download');
    else iconSet.add('Sparkles');
  });

  const importsList = Array.from(iconSet).join(', ');

  // Ensure unique component names
  const usedNames = new Set<string>();
  const componentEntries = components.map((comp, idx) => {
    let baseName = toPascalCase(comp.content.label || `Button${idx + 1}`);
    if (!baseName.endsWith('Button')) {
      baseName = `${baseName}Button`;
    }
    let uniqueName = baseName;
    let counter = 2;
    while (usedNames.has(uniqueName)) {
      uniqueName = `${baseName}_${counter++}`;
    }
    usedNames.add(uniqueName);
    return { comp, componentName: uniqueName };
  });

  const hasAnyDynamicShadow = components.some(c =>
    c.effects.special_features.includes('dynamic_shadow_cursor_tracking')
  );
  const hasAnyRGB = components.some(c =>
    c.effects.special_features.includes('rgb_running_border')
  );

  const individualComponentsCode = componentEntries
    .map(({ comp, componentName }) => {
      const isRGB = comp.effects.special_features.includes('rgb_running_border');
      const isDynamicShadow = comp.effects.special_features.includes(
        'dynamic_shadow_cursor_tracking'
      );

      return `/**
 * [${comp.content.label}] - Category: ${comp.type.toUpperCase()} | Section: ${comp.location.section}
 * ARIA: "${comp.accessibility.aria_label}"
 */
export const ${componentName}: React.FC<LivingButtonProps> = ({
  onClick,
  disabled = false,
  className = '',
  children,
}) => {
  const [state, setState] = useState<'idle' | 'hover' | 'loading' | 'success' | 'error'>('idle');
  const buttonRef = useRef<HTMLButtonElement>(null);

  ${
    isDynamicShadow
      ? `useDynamicCursorShadow(buttonRef, disabled || state === 'loading', ${tokens.shadowIntensity});`
      : ''
  }

  const handleClick = async (e: React.MouseEvent<HTMLButtonElement>) => {
    if (disabled || state === 'loading') return;
    setState('loading');
    try {
      if (onClick) await onClick();
      setState('success');
      setTimeout(() => setState('idle'), 1500);
    } catch {
      setState('error');
      setTimeout(() => setState('idle'), 1200);
    }
  };

  return (
    <button
      ref={buttonRef}
      id="${comp.id}"
      type="button"
      tabIndex={${comp.accessibility.tab_index}}
      aria-label="${comp.accessibility.aria_label}"
      disabled={disabled || state === 'loading'}
      onClick={handleClick}
      onMouseEnter={() => setState('hover')}
      onMouseLeave={() => state !== 'loading' && state !== 'success' && setState('idle')}
      className={\`group relative inline-flex items-center justify-center gap-2.5 px-6 py-3 text-sm font-semibold tracking-wide transition-all duration-200 outline-none select-none
        ${isRGB ? 'living-btn-rgb' : getBaseStyleClasses(comp.effects.base_style)}
        \${state === 'loading' ? 'cursor-wait opacity-85' : 'cursor-pointer'}
        \${state === 'error' ? 'animate-shake !bg-rose-600 !text-white' : ''}
        \${state === 'success' ? 'animate-success-pop !bg-emerald-600 !text-white' : ''}
        \${disabled ? 'opacity-40 cursor-not-allowed filter grayscale' : 'hover:scale-[1.02] active:scale-[0.98]'}
        \${className}\`}
      style={{
        borderRadius: '${tokens.borderRadius === 9999 ? '9999px' : `${tokens.borderRadius}px`}',
        ['--btn-transition-timing' as any]: '${tokens.transitionTiming}',
        transitionTimingFunction: '${tokens.transitionTiming}',
      }}
    >
      {state === 'loading' ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin text-cyan-300" />
          <span>Processing...</span>
        </>
      ) : state === 'success' ? (
        <>
          <Check className="w-4 h-4 text-white" />
          <span>Success</span>
        </>
      ) : (
        <>
          ${renderIconJSX(comp.content.icon_name)}
          <span>{children || '${comp.content.label}'}</span>
        </>
      )}
    </button>
  );
};`;
    })
    .join('\n\n');

  return `${getMultiAttributionHeader(components)}import React, { useState, useRef, useEffect } from 'react';
import { ${importsList} } from 'lucide-react';

/* ==========================================================================
 * Design Tokens Configuration
 * ========================================================================== */
export const BUNDLE_TOKENS = ${JSON.stringify(tokens, null, 2)} as const;

export interface LivingButtonProps {
  onClick?: () => void | Promise<void>;
  disabled?: boolean;
  className?: string;
  children?: React.ReactNode;
}

${
  hasAnyDynamicShadow
    ? `/**
 * Custom Hook for Dynamic Cursor Proximity Shadow Tracking
 */
function useDynamicCursorShadow(
  ref: React.RefObject<HTMLButtonElement>,
  disabled: boolean,
  intensity: number = ${tokens.shadowIntensity}
) {
  useEffect(() => {
    const btn = ref.current;
    if (!btn || disabled) return;

    const handleMouseMove = (event: MouseEvent) => {
      const bounds = btn.getBoundingClientRect();
      const centerX = bounds.left + bounds.width / 2;
      const centerY = bounds.top + bounds.height / 2;

      const diffX = event.clientX - centerX;
      const diffY = event.clientY - centerY;

      const shadowOffsetX = -(diffX / 16);
      const shadowOffsetY = -(diffY / 16);

      const distance = Math.sqrt(diffX * diffX + diffY * diffY);
      const blurRadius = Math.min(28, Math.max(8, 3500 / (distance + 1)));

      btn.style.boxShadow = \`\${shadowOffsetX.toFixed(1)}px \${shadowOffsetY.toFixed(1)}px \${blurRadius.toFixed(1)}px rgba(0, 0, 0, \${intensity})\`;
    };

    const handleMouseLeave = () => {
      btn.style.boxShadow = '';
    };

    window.addEventListener('mousemove', handleMouseMove);
    btn.addEventListener('mouseleave', handleMouseLeave);
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      btn.removeEventListener('mouseleave', handleMouseLeave);
    };
  }, [ref, disabled, intensity]);
}
`
    : ''
}
/* ==========================================================================
 * Individual Button Components (${components.length} Total)
 * ========================================================================== */

${individualComponentsCode}

/* ==========================================================================
 * Interactive Bundle Gallery & Component Dictionary
 * ========================================================================== */

export const ButtonBundleMap = {
${componentEntries.map(e => `  ${e.componentName}: ${e.componentName},`).join('\n')}
};

export const ButtonBundleGallery: React.FC<{ className?: string }> = ({ className = '' }) => {
  return (
    <div className={\`flex flex-wrap items-center gap-4 p-6 bg-neutral-950 rounded-2xl border border-neutral-800 \${className}\`}>
${componentEntries
  .map(
    e => `      <div className="flex flex-col items-center gap-1.5">
        <${e.componentName} />
        <span className="text-[10px] font-mono text-neutral-500">${e.comp.id}</span>
      </div>`
  )
  .join('\n')}
    </div>
  );
};

export default ButtonBundleGallery;
`;
}

export function generateHtmlCssCode(component: AIButtonStudioComponent, tokens: DesignTokens): string {
  const isRGB = component.effects.special_features.includes('rgb_running_border');
  const isDynamicShadow = component.effects.special_features.includes('dynamic_shadow_cursor_tracking');

  return `${getAttributionHeader(component.attribution)}<!-- HTML Button Markup -->
<button
  id="${component.id}"
  class="living-btn ${isRGB ? 'living-btn-rgb' : ''}"
  aria-label="${component.accessibility.aria_label}"
  tabindex="${component.accessibility.tab_index}"
>
  <span class="btn-content">
    <span class="btn-label">${component.content.label}</span>
  </span>
</button>

<style>
:root {
  --btn-radius: ${tokens.borderRadius === 9999 ? '9999px' : `${tokens.borderRadius}px`};
  --border-thickness: ${tokens.borderThickness}px;
  --rgb-duration: ${tokens.rgbDuration}s;
  --shadow-intensity: ${tokens.shadowIntensity};
  --btn-transition-timing: ${tokens.transitionTiming};
}

.living-btn {
  position: relative;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 12px 24px;
  font-family: system-ui, sans-serif;
  font-size: 14px;
  font-weight: 600;
  color: #ffffff;
  background: #0f172a;
  border-radius: var(--btn-radius);
  border: 1px solid rgba(255, 255, 255, 0.15);
  cursor: pointer;
  outline: none;
  transition: all 0.25s var(--btn-transition-timing, cubic-bezier(0.4, 0, 0.2, 1));
}

${isRGB ? `/* RGB Conic Gradient Implementation */
.living-btn-rgb {
  border: none;
  overflow: hidden;
  z-index: 1;
}

.living-btn-rgb::before {
  content: '';
  position: absolute;
  top: -50%;
  left: -50%;
  width: 200%;
  height: 200%;
  background: conic-gradient(#ff0055, #fe9000, #fff020, #3edf4b, #3363ff, #b102b7, #ff0055);
  animation: rotate-border var(--rgb-duration) linear infinite;
  z-index: -2;
  transition: animation-duration 0.3s ease;
}

.living-btn-rgb::after {
  content: '';
  position: absolute;
  inset: var(--border-thickness);
  background: #111827;
  border-radius: calc(var(--btn-radius) - var(--border-thickness));
  z-index: -1;
}

.living-btn-rgb:hover {
  --rgb-duration: 0.8s;
}

.living-btn-rgb:active {
  filter: brightness(1.3);
}

@keyframes rotate-border {
  100% { transform: rotate(360deg); }
}` : ''}
</style>

${isDynamicShadow ? `<script>
// Dynamic Cursor Tracking Shadow (Section 3.3.A)
const btn = document.getElementById('${component.id}');
if (btn) {
  document.addEventListener('mousemove', (event) => {
    const bounds = btn.getBoundingClientRect();
    const centerX = bounds.left + bounds.width / 2;
    const centerY = bounds.top + bounds.height / 2;

    const diffX = event.clientX - centerX;
    const diffY = event.clientY - centerY;

    const shadowOffsetX = -(diffX / 15);
    const shadowOffsetY = -(diffY / 15);
    const distance = Math.sqrt(diffX * diffX + diffY * diffY);
    const blurRadius = Math.min(30, Math.max(10, 4000 / distance));

    btn.style.boxShadow = \`\${shadowOffsetX}px \${shadowOffsetY}px \${blurRadius}px rgba(0, 0, 0, ${tokens.shadowIntensity})\`;
  });
}
</script>` : ''}
`;
}

/**
 * Generates bundled HTML + CSS markup for all selected components
 */
export function generateBundledHtmlCssCode(
  components: AIButtonStudioComponent[],
  tokens: DesignTokens
): string {
  if (components.length === 0) {
    return `<!-- No components selected for export -->`;
  }

  const buttonsHtml = components
    .map(comp => {
      const isRGB = comp.effects.special_features.includes('rgb_running_border');
      return `  <!-- Button: ${comp.content.label} (${comp.id}) -->
  <button
    id="${comp.id}"
    class="living-btn ${isRGB ? 'living-btn-rgb' : ''}"
    aria-label="${comp.accessibility.aria_label}"
    tabindex="${comp.accessibility.tab_index}"
  >
    <span class="btn-content">
      <span class="btn-label">${comp.content.label}</span>
    </span>
  </button>`;
    })
    .join('\n\n');

  return `${getMultiAttributionHeader(components)}<!-- Multi-Button HTML Bundle -->
<div class="living-buttons-bundle">
${buttonsHtml}
</div>

<style>
:root {
  --btn-radius: ${tokens.borderRadius === 9999 ? '9999px' : `${tokens.borderRadius}px`};
  --border-thickness: ${tokens.borderThickness}px;
  --rgb-duration: ${tokens.rgbDuration}s;
  --shadow-intensity: ${tokens.shadowIntensity};
  --btn-transition-timing: ${tokens.transitionTiming};
}

.living-buttons-bundle {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 16px;
  padding: 24px;
  background: #09090b;
  border-radius: 16px;
}

.living-btn {
  position: relative;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 12px 24px;
  font-family: system-ui, -apple-system, sans-serif;
  font-size: 14px;
  font-weight: 600;
  color: #ffffff;
  background: #0f172a;
  border-radius: var(--btn-radius);
  border: 1px solid rgba(255, 255, 255, 0.15);
  cursor: pointer;
  outline: none;
  transition: all 0.25s var(--btn-transition-timing);
}

.living-btn:hover {
  transform: translateY(-2px);
}

/* RGB Conic Gradient Implementation */
.living-btn-rgb {
  border: none;
  overflow: hidden;
  z-index: 1;
}

.living-btn-rgb::before {
  content: '';
  position: absolute;
  top: -50%;
  left: -50%;
  width: 200%;
  height: 200%;
  background: conic-gradient(#ff0055, #fe9000, #fff020, #3edf4b, #3363ff, #b102b7, #ff0055);
  animation: rotate-border var(--rgb-duration) linear infinite;
  z-index: -2;
  transition: animation-duration 0.3s ease;
}

.living-btn-rgb::after {
  content: '';
  position: absolute;
  inset: var(--border-thickness);
  background: #111827;
  border-radius: calc(var(--btn-radius) - var(--border-thickness));
  z-index: -1;
}

@keyframes rotate-border {
  100% { transform: rotate(360deg); }
}
</style>
`;
}

export function generateVueCode(component: AIButtonStudioComponent, tokens: DesignTokens): string {
  return `${getAttributionHeader(component.attribution)}<template>
  <button
    id="${component.id}"
    :class="[
      'living-btn',
      '${component.effects.special_features.includes('rgb_running_border') ? 'living-btn-rgb' : ''}',
      { 'is-loading': loading }
    ]"
    :aria-label="'${component.accessibility.aria_label}'"
    :tabindex="${component.accessibility.tab_index}"
    @click="handleClick"
  >
    <span v-if="loading">Processing...</span>
    <span v-else>${component.content.label}</span>
  </button>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const loading = ref(false);

const emit = defineEmits(['click']);

const handleClick = async () => {
  if (loading.value) return;
  loading.value = true;
  emit('click');
  setTimeout(() => { loading.value = false; }, 1200);
};
</script>

<style scoped>
.living-btn {
  padding: 12px 24px;
  border-radius: ${tokens.borderRadius === 9999 ? '9999px' : `${tokens.borderRadius}px`};
  background: #0f172a;
  color: #ffffff;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.25s ${tokens.transitionTiming};
}
</style>
`;
}

/**
 * Generates bundled Vue 3 SFC component containing all selected buttons
 */
export function generateBundledVueCode(
  components: AIButtonStudioComponent[],
  tokens: DesignTokens
): string {
  return `${getMultiAttributionHeader(components)}<template>
  <div class="living-buttons-bundle">
    <button
      v-for="btn in buttons"
      :key="btn.id"
      :id="btn.id"
      :class="[
        'living-btn',
        { 'living-btn-rgb': btn.isRGB },
        { 'is-loading': activeLoadingId === btn.id }
      ]"
      :aria-label="btn.ariaLabel"
      :tabindex="btn.tabIndex"
      @click="handleButtonClick(btn)"
    >
      <span v-if="activeLoadingId === btn.id">Processing...</span>
      <span v-else>{{ btn.label }}</span>
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

interface ButtonItem {
  id: string;
  label: string;
  isRGB: boolean;
  ariaLabel: string;
  tabIndex: number;
}

const activeLoadingId = ref<string | null>(null);
const emit = defineEmits(['buttonClick']);

const buttons: ButtonItem[] = [
${components
  .map(
    c => `  {
    id: '${c.id}',
    label: '${c.content.label}',
    isRGB: ${c.effects.special_features.includes('rgb_running_border')},
    ariaLabel: '${c.accessibility.aria_label}',
    tabIndex: ${c.accessibility.tab_index},
  },`
  )
  .join('\n')}
];

const handleButtonClick = async (btn: ButtonItem) => {
  if (activeLoadingId.value) return;
  activeLoadingId.value = btn.id;
  emit('buttonClick', btn);
  setTimeout(() => {
    activeLoadingId.value = null;
  }, 1200);
};
</script>

<style scoped>
.living-buttons-bundle {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  padding: 24px;
  background: #09090b;
  border-radius: 16px;
}

.living-btn {
  padding: 12px 24px;
  border-radius: ${tokens.borderRadius === 9999 ? '9999px' : `${tokens.borderRadius}px`};
  background: #0f172a;
  color: #ffffff;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.25s ${tokens.transitionTiming};
  border: 1px solid rgba(255, 255, 255, 0.15);
}
</style>
`;
}

/**
 * Generates Tailwind CSS utility classes and configuration snippets for a single button
 */
export function generateTailwindCode(component: AIButtonStudioComponent, tokens: DesignTokens): string {
  const isRGB = component.effects.special_features.includes('rgb_running_border');
  const baseStyle = getBaseStyleClasses(component.effects.base_style);
  const radiusClass =
    tokens.borderRadius === 9999
      ? 'rounded-full'
      : tokens.borderRadius === 0
      ? 'rounded-none'
      : tokens.borderRadius <= 4
      ? 'rounded-sm'
      : tokens.borderRadius <= 8
      ? 'rounded-md'
      : tokens.borderRadius <= 12
      ? 'rounded-lg'
      : tokens.borderRadius <= 16
      ? 'rounded-xl'
      : tokens.borderRadius <= 24
      ? 'rounded-2xl'
      : `rounded-[${tokens.borderRadius}px]`;

  const coreClasses = [
    'group',
    'relative',
    'inline-flex',
    'items-center',
    'justify-center',
    'gap-2.5',
    'px-6',
    'py-3',
    'text-sm',
    'font-semibold',
    'tracking-wide',
    radiusClass,
    'transition-all',
    'duration-200',
    'outline-none',
    'select-none',
    'hover:scale-[1.02]',
    'active:scale-[0.98]',
    'focus-visible:ring-2',
    'focus-visible:ring-cyan-400',
    'focus-visible:ring-offset-2',
    'focus-visible:ring-offset-neutral-950',
    'disabled:opacity-40',
    'disabled:cursor-not-allowed',
    'disabled:pointer-events-none',
    'disabled:filter',
    'disabled:grayscale',
    isRGB ? 'living-btn-rgb' : baseStyle,
  ]
    .filter(Boolean)
    .join(' ');

  const componentName = toPascalCase(component.content.label || 'LivingButton');

  return `${getAttributionHeader(component.attribution)}/**
 * ============================================================================
 * Tailwind CSS Utility Class Exports
 * Component: ${component.content.label} (${component.id})
 * ============================================================================
 */

// 1. Drop-In Tailwind Utility Class String (for className="...")
export const ${componentName}Classes =
  "${coreClasses}";

// 2. Breakdown of Tailwind Classes by Interaction State
export const ${componentName}StateDictionary = {
  base: "relative inline-flex items-center justify-center gap-2.5 px-6 py-3 text-sm font-semibold tracking-wide ${radiusClass} outline-none select-none transition-all duration-200 ${isRGB ? 'border border-transparent' : baseStyle}",
  hover: "hover:scale-[1.02] hover:brightness-110",
  active: "active:scale-[0.98] active:brightness-95",
  focus: "focus-visible:ring-2 focus-visible:ring-cyan-400 focus-visible:ring-offset-2 focus-visible:ring-offset-neutral-950",
  disabled: "disabled:opacity-40 disabled:cursor-not-allowed disabled:pointer-events-none disabled:grayscale",
  loading: "cursor-wait opacity-85 pointer-events-none",
  success: "animate-success-pop !bg-emerald-600 !text-white shadow-emerald-500/40",
  error: "animate-shake !bg-rose-600 !text-white shadow-rose-500/40",
};

/**
 * 3. Tailwind CSS @apply Directive (paste into globals.css or @layer components)
 */
/*
@layer components {
  .${component.id.toLowerCase().replace(/[^a-z0-9]/g, '-')} {
    @apply ${coreClasses.replace(/living-btn-rgb/g, '')};
  }
}
*/

/**
 * 4. JSX Quick Drop-in Example:
 * <button
 *   id="${component.id}"
 *   type="button"
 *   aria-label="${component.accessibility.aria_label}"
 *   tabIndex={${component.accessibility.tab_index}}
 *   className="${coreClasses}"
 * >
 *   <span>${component.content.label}</span>
 * </button>
 */
`;
}

/**
 * Generates consolidated Tailwind utility class mappings for multi-component bundles
 */
export function generateBundledTailwindCode(components: AIButtonStudioComponent[], tokens: DesignTokens): string {
  const dateStr = new Date().toISOString();
  const radiusClass =
    tokens.borderRadius === 9999
      ? 'rounded-full'
      : tokens.borderRadius === 0
      ? 'rounded-none'
      : tokens.borderRadius <= 4
      ? 'rounded-sm'
      : tokens.borderRadius <= 8
      ? 'rounded-md'
      : tokens.borderRadius <= 12
      ? 'rounded-lg'
      : tokens.borderRadius <= 16
      ? 'rounded-xl'
      : tokens.borderRadius <= 24
      ? 'rounded-2xl'
      : `rounded-[${tokens.borderRadius}px]`;

  return `${getMultiAttributionHeader(components)}/**
 * ============================================================================
 * Tailwind CSS Utility Class Dictionary (Consolidated Multi-Button Bundle)
 * Selected Items: ${components.length}
 * Generated: ${dateStr}
 * ============================================================================
 */

export const ButtonTailwindDictionary = {
${components
  .map(comp => {
    const isRGB = comp.effects.special_features.includes('rgb_running_border');
    const baseStyle = getBaseStyleClasses(comp.effects.base_style);
    const classes = `group relative inline-flex items-center justify-center gap-2.5 px-6 py-3 text-sm font-semibold tracking-wide ${radiusClass} transition-all duration-200 outline-none select-none hover:scale-[1.02] active:scale-[0.98] focus-visible:ring-2 focus-visible:ring-cyan-400 focus-visible:ring-offset-2 focus-visible:ring-offset-neutral-950 disabled:opacity-40 disabled:cursor-not-allowed ${isRGB ? 'living-btn-rgb' : baseStyle}`;
    return `  /** ${comp.content.label} (${comp.id}) */
  "${comp.id}": "${classes}",`;
  })
  .join('\n\n')}
} as const;

/**
 * Consolidated @layer components CSS rules
 */
/*
@layer components {
${components
  .map(comp => {
    const isRGB = comp.effects.special_features.includes('rgb_running_border');
    const baseStyle = getBaseStyleClasses(comp.effects.base_style);
    const classes = `group relative inline-flex items-center justify-center gap-2.5 px-6 py-3 text-sm font-semibold tracking-wide ${radiusClass} transition-all duration-200 outline-none select-none hover:scale-[1.02] active:scale-[0.98] focus-visible:ring-2 focus-visible:ring-cyan-400 focus-visible:ring-offset-2 focus-visible:ring-offset-neutral-950 disabled:opacity-40 disabled:cursor-not-allowed ${isRGB ? '' : baseStyle}`;
    const className = `btn-${comp.content.label.toLowerCase().replace(/[^a-z0-9]/g, '-') || comp.id}`;
    return `  .${className} {
    @apply ${classes};
  }`;
  })
  .join('\n\n')}
}
*/
`;
}

/**
 * Generates an isolated CSS Module for a single button
 */
export function generateCssModuleCode(component: AIButtonStudioComponent, tokens: DesignTokens): string {
  const isRGB = component.effects.special_features.includes('rgb_running_border');
  const baseStyle = component.effects.base_style;
  const radius = tokens.borderRadius === 9999 ? '9999px' : `${tokens.borderRadius}px`;
  const componentName = toPascalCase(component.content.label || 'LivingButton');

  return `/**
 * ============================================================================
 * ${component.content.label} - CSS Module Stylesheet
 * File: ${componentName}.module.css
 * Author / Credit: ${component.attribution.credit_owner}
 * License: ${component.attribution.license_type}
 * ============================================================================
 * 
 * USAGE (React / Next.js / Vite):
 * import styles from './${componentName}.module.css';
 * 
 * <button
 *   id="${component.id}"
 *   type="button"
 *   aria-label="${component.accessibility.aria_label}"
 *   tabIndex={${component.accessibility.tab_index}}
 *   className={\`\${styles.button} ${isRGB ? '${styles.buttonRgb}' : ''}\`}
 * >
 *   <span className={styles.content}>
 *     <span className={styles.label}>${component.content.label}</span>
 *   </span>
 * </button>
 */

/* Scoped Component Design Variables */
.button {
  --btn-radius: ${radius};
  --border-thickness: ${tokens.borderThickness}px;
  --rgb-duration: ${tokens.rgbDuration}s;
  --shadow-intensity: ${tokens.shadowIntensity};
  --btn-transition-timing: ${tokens.transitionTiming};
  --primary-hue: ${tokens.primaryHue};
  --accent-color: ${tokens.accentColor};

  position: relative;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  padding: 12px 24px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
  font-size: 14px;
  font-weight: 600;
  letter-spacing: 0.025em;
  color: #ffffff;
  border-radius: var(--btn-radius);
  outline: none;
  user-select: none;
  cursor: pointer;
  box-sizing: border-box;
  transition: all 0.2s var(--btn-transition-timing, cubic-bezier(0.4, 0, 0.2, 1));

  /* Base Visual Style: ${baseStyle} */
  ${getCssModuleBaseTheme(baseStyle)}
}

/* Hover, Active, and Focus States */
.button:hover:not(:disabled) {
  transform: scale(1.02);
  ${baseStyle === 'neon_blue_glow' ? 'box-shadow: 0 0 30px rgba(6, 182, 212, 0.55); border-color: rgba(34, 211, 238, 0.9); color: #ecfeff;' : ''}
  ${baseStyle === 'gradient_fill' ? 'filter: brightness(1.1); box-shadow: 0 10px 25px -5px rgba(99, 102, 241, 0.5);' : ''}
  ${baseStyle === 'soft_shadow' ? 'background: #262626; border-color: #525252;' : ''}
  ${baseStyle === 'outline_rgb' ? 'border-color: #22d3ee; background: rgba(23, 23, 23, 0.95);' : ''}
}

.button:active:not(:disabled) {
  transform: scale(0.98);
  filter: brightness(0.95);
}

.button:focus-visible {
  outline: 2px solid #22d3ee;
  outline-offset: 2px;
}

.button:disabled {
  opacity: 0.4;
  cursor: not-allowed;
  pointer-events: none;
  filter: grayscale(100%);
}

/* Dynamic State Modifiers */
.isLoading {
  cursor: wait;
  opacity: 0.85;
  pointer-events: none;
}

.isSuccess {
  background: #059669 !important;
  color: #ffffff !important;
  border-color: #10b981 !important;
  box-shadow: 0 0 20px rgba(16, 185, 129, 0.4) !important;
  animation: successPop 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}

.isError {
  background: #e11d48 !important;
  color: #ffffff !important;
  border-color: #f43f5e !important;
  box-shadow: 0 0 20px rgba(244, 63, 94, 0.4) !important;
  animation: errorShake 0.4s cubic-bezier(0.36, 0.07, 0.19, 0.97);
}

/* Inner Layout Elements */
.content {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  position: relative;
  z-index: 1;
}

.label {
  white-space: nowrap;
}

.icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 16px;
  height: 16px;
  transition: transform 0.2s ease;
}

.button:hover .icon {
  transform: translateX(2px);
}

${isRGB ? `/* RGB Conic Gradient Running Border */
.buttonRgb {
  border: none !important;
  overflow: hidden;
  position: relative;
  z-index: 1;
}

.buttonRgb::before {
  content: '';
  position: absolute;
  top: -50%;
  left: -50%;
  width: 200%;
  height: 200%;
  background: conic-gradient(#ff0055, #fe9000, #fff020, #3edf4b, #3363ff, #b102b7, #ff0055);
  animation: rotateBorder var(--rgb-duration) linear infinite;
  z-index: -2;
}

.buttonRgb::after {
  content: '';
  position: absolute;
  inset: var(--border-thickness);
  background: #0f172a;
  border-radius: calc(var(--btn-radius) - var(--border-thickness));
  z-index: -1;
}

.buttonRgb:hover::before {
  animation-duration: 0.8s;
}
` : ''}

/* Keyframe Animations */
@keyframes rotateBorder {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

@keyframes successPop {
  0% { transform: scale(0.95); }
  50% { transform: scale(1.05); }
  100% { transform: scale(1); }
}

@keyframes errorShake {
  10%, 90% { transform: translate3d(-1px, 0, 0); }
  20%, 80% { transform: translate3d(2px, 0, 0); }
  30%, 50%, 70% { transform: translate3d(-4px, 0, 0); }
  40%, 60% { transform: translate3d(4px, 0, 0); }
}

/* Reduced Motion Override */
@media (prefers-reduced-motion: reduce) {
  .button,
  .buttonRgb::before,
  .icon,
  .isSuccess,
  .isError {
    animation: none !important;
    transition: none !important;
  }
}
`;
}

/**
 * Generates consolidated CSS Module styles for multi-component bundles
 */
export function generateBundledCssModuleCode(components: AIButtonStudioComponent[], tokens: DesignTokens): string {
  const radius = tokens.borderRadius === 9999 ? '9999px' : `${tokens.borderRadius}px`;

  return `${getMultiAttributionHeader(components)}/**
 * ============================================================================
 * AI Button Studio - Consolidated CSS Module Bundle
 * File: ButtonBundle.module.css
 * ============================================================================
 * 
 * USAGE:
 * import styles from './ButtonBundle.module.css';
 * 
 * <button className={styles.btn_${components[0]?.id || 'button'}}>
 *   <span className={styles.label}>${components[0]?.content.label || 'Button'}</span>
 * </button>
 */

/* Shared Root Design Variables */
:root {
  --btn-radius: ${radius};
  --border-thickness: ${tokens.borderThickness}px;
  --rgb-duration: ${tokens.rgbDuration}s;
  --shadow-intensity: ${tokens.shadowIntensity};
  --btn-transition-timing: ${tokens.transitionTiming};
}

/* Shared Base Button */
.livingButtonBase {
  position: relative;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  padding: 12px 24px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
  font-size: 14px;
  font-weight: 600;
  letter-spacing: 0.025em;
  color: #ffffff;
  border-radius: var(--btn-radius);
  outline: none;
  user-select: none;
  cursor: pointer;
  box-sizing: border-box;
  transition: all 0.2s var(--btn-transition-timing, cubic-bezier(0.4, 0, 0.2, 1));
}

.livingButtonBase:hover:not(:disabled) {
  transform: scale(1.02);
}

.livingButtonBase:active:not(:disabled) {
  transform: scale(0.98);
}

.livingButtonBase:focus-visible {
  outline: 2px solid #22d3ee;
  outline-offset: 2px;
}

.livingButtonBase:disabled {
  opacity: 0.4;
  cursor: not-allowed;
  pointer-events: none;
  filter: grayscale(100%);
}

.label {
  white-space: nowrap;
}

/* Individual Component Variants */
${components
  .map(comp => {
    const isRGB = comp.effects.special_features.includes('rgb_running_border');
    const baseStyle = comp.effects.base_style;
    const className = `btn_${comp.id.replace(/[^a-zA-Z0-9_]/g, '_')}`;

    return `/* ${comp.content.label} (${comp.id}) */
.${className} {
  composes: livingButtonBase;
  ${getCssModuleBaseTheme(baseStyle)}
  ${isRGB ? `border: none !important;
  overflow: hidden;` : ''}
}`;
  })
  .join('\n\n')}

/* Animation Keyframes */
@keyframes rotateBorder {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

@keyframes successPop {
  0% { transform: scale(0.95); }
  50% { transform: scale(1.05); }
  100% { transform: scale(1); }
}

@keyframes errorShake {
  10%, 90% { transform: translate3d(-1px, 0, 0); }
  20%, 80% { transform: translate3d(2px, 0, 0); }
  30%, 50%, 70% { transform: translate3d(-4px, 0, 0); }
  40%, 60% { transform: translate3d(4px, 0, 0); }
}
`;
}

function getCssModuleBaseTheme(style: string): string {
  switch (style) {
    case 'neon_blue_glow':
      return `background: rgba(8, 51, 68, 0.85);
  color: #a5f3fc;
  border: 1px solid rgba(6, 182, 212, 0.5);
  box-shadow: 0 0 20px rgba(6, 182, 212, 0.35);`;
    case 'gradient_fill':
      return `background: linear-gradient(135deg, #0ea5e9, #6366f1, #9333ea);
  color: #ffffff;
  border: 1px solid rgba(255, 255, 255, 0.15);
  box-shadow: 0 10px 20px -5px rgba(99, 102, 241, 0.35);`;
    case 'outline_rgb':
      return `background: rgba(23, 23, 23, 0.9);
  color: #ffffff;
  border: 1px solid #404040;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);`;
    case 'soft_shadow':
      return `background: #1f2937;
  color: #f3f4f6;
  border: 1px solid rgba(75, 85, 99, 0.6);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.45);`;
    default:
      return `background: #0284c7;
  color: #ffffff;
  border: 1px solid rgba(255, 255, 255, 0.2);
  box-shadow: 0 4px 12px rgba(2, 132, 199, 0.3);`;
  }
}

function toPascalCase(str: string): string {
  return (
    str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map(w => w.charAt(0).toUpperCase() + w.slice(1))
      .join('') || 'LivingButton'
  );
}

function getBaseStyleClasses(style: string): string {
  switch (style) {
    case 'neon_blue_glow':
      return 'bg-cyan-950/80 text-cyan-200 border border-cyan-500/50 shadow-[0_0_20px_rgba(6,182,212,0.3)] hover:shadow-[0_0_30px_rgba(6,182,212,0.55)] hover:border-cyan-400';
    case 'gradient_fill':
      return 'bg-gradient-to-r from-sky-500 via-indigo-500 to-purple-600 text-white shadow-lg shadow-indigo-500/25 hover:shadow-indigo-500/45';
    case 'outline_rgb':
      return 'bg-neutral-900/90 text-white border border-neutral-700';
    case 'soft_shadow':
      return 'bg-neutral-800 text-neutral-100 border border-neutral-700/60 shadow-md shadow-black/40 hover:bg-neutral-750';
    default:
      return 'bg-sky-600 text-white shadow-md hover:bg-sky-500';
  }
}

function renderIconJSX(iconName?: string): string {
  switch (iconName) {
    case 'rocket':
      return '<Rocket className="w-4 h-4 text-cyan-300 group-hover:translate-x-0.5 transition-transform" />';
    case 'sparkles':
      return '<Sparkles className="w-4 h-4 text-amber-300 group-hover:rotate-12 transition-transform" />';
    case 'search':
      return '<Search className="w-4 h-4 text-neutral-300" />';
    case 'plus':
      return '<Plus className="w-4 h-4 text-white group-hover:rotate-90 transition-transform" />';
    case 'arrow-right':
      return '<ArrowRight className="w-4 h-4 text-cyan-400 group-hover:translate-x-1 transition-transform" />';
    case 'check':
      return '<Check className="w-4 h-4 text-emerald-400" />';
    case 'play':
      return '<Play className="w-4 h-4 text-emerald-300" />';
    case 'download':
      return '<Download className="w-4 h-4 text-sky-300" />';
    default:
      return '<Sparkles className="w-4 h-4 text-cyan-300" />';
  }
}

/**
 * Generates an isolated React TSX file paired with its dedicated CSS Module file
 */
export function generateReactWithCssModule(
  component: AIButtonStudioComponent,
  tokens: DesignTokens
): { componentName: string; tsx: string; cssModule: string } {
  const componentName = toPascalCase(component.content.label || 'LivingButton');
  const isRGB = component.effects.special_features.includes('rgb_running_border');
  const isDynamicShadow = component.effects.special_features.includes('dynamic_shadow_cursor_tracking');
  const cssModule = generateCssModuleCode(component, tokens);

  const tsx = `${getAttributionHeader(component.attribution)}import React, { useState, useRef, useEffect } from 'react';
import { Sparkles, Rocket, Search, Plus, ArrowRight, Check, Loader2, Play, Download } from 'lucide-react';
import styles from './${componentName}.module.css';

export interface ${componentName}Props {
  /** Optional click handler (can be async) */
  onClick?: () => void | Promise<void>;
  /** Disabled state */
  disabled?: boolean;
  /** Custom extra CSS classes */
  className?: string;
  /** Custom button text override */
  children?: React.ReactNode;
}

/**
 * ${componentName} Component
 * Action: ${component.action.type} -> ${component.action.target}
 * Base Style: ${component.effects.base_style}
 * Special Features: ${component.effects.special_features.join(', ') || 'none'}
 */
export const ${componentName}: React.FC<${componentName}Props> = ({
  onClick,
  disabled = false,
  className = '',
  children,
}) => {
  const [state, setState] = useState<'idle' | 'hover' | 'loading' | 'success' | 'error'>('idle');
  const buttonRef = useRef<HTMLButtonElement>(null);

  ${isDynamicShadow ? `// Proximity Shadow Tracking
  useEffect(() => {
    const btn = buttonRef.current;
    if (!btn || disabled || state === 'loading') return;

    const handleMouseMove = (event: MouseEvent) => {
      const bounds = btn.getBoundingClientRect();
      const centerX = bounds.left + bounds.width / 2;
      const centerY = bounds.top + bounds.height / 2;

      const diffX = event.clientX - centerX;
      const diffY = event.clientY - centerY;

      const shadowOffsetX = -(diffX / 16);
      const shadowOffsetY = -(diffY / 16);

      const distance = Math.sqrt(diffX * diffX + diffY * diffY);
      const blurRadius = Math.min(28, Math.max(8, 3500 / (distance + 1)));

      btn.style.boxShadow = \`\${shadowOffsetX.toFixed(1)}px \${shadowOffsetY.toFixed(1)}px \${blurRadius.toFixed(1)}px rgba(0, 0, 0, ${tokens.shadowIntensity})\`;
    };

    const handleMouseLeave = () => {
      btn.style.boxShadow = '';
    };

    window.addEventListener('mousemove', handleMouseMove);
    btn.addEventListener('mouseleave', handleMouseLeave);
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      btn.removeEventListener('mouseleave', handleMouseLeave);
    };
  }, [disabled, state]);` : ''}

  const handleClick = async (e: React.MouseEvent<HTMLButtonElement>) => {
    if (disabled || state === 'loading') return;
    setState('loading');

    try {
      if (onClick) {
        await onClick();
      }
      setState('success');
      setTimeout(() => setState('idle'), 1800);
    } catch {
      setState('error');
      setTimeout(() => setState('idle'), 2000);
    }
  };

  const buttonClasses = [
    styles.button,
    ${isRGB ? 'styles.buttonRgb,' : ''}
    state === 'loading' ? styles.isLoading : '',
    state === 'success' ? styles.isSuccess : '',
    state === 'error' ? styles.isError : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <button
      ref={buttonRef}
      id="${component.id}"
      type="button"
      disabled={disabled}
      aria-label="${component.accessibility.aria_label}"
      aria-busy={state === 'loading'}
      aria-disabled={disabled}
      tabIndex={${component.accessibility.tab_index}}
      onClick={handleClick}
      onMouseEnter={() => state === 'idle' && setState('hover')}
      onMouseLeave={() => state === 'hover' && setState('idle')}
      className={buttonClasses}
    >
      <span className={styles.content}>
        {state === 'loading' && (
          <Loader2 className="w-4 h-4 animate-spin text-white" />
        )}
        {state === 'success' && (
          <Check className="w-4 h-4 text-emerald-300" />
        )}
        {state !== 'loading' && state !== 'success' && (
          <span className={styles.icon}>
            ${renderIconJSX(component.content.icon_name)}
          </span>
        )}
        <span className={styles.label}>
          {children || (
            state === 'loading'
              ? 'Processing...'
              : state === 'success'
              ? 'Complete!'
              : state === 'error'
              ? 'Failed'
              : '${component.content.label}')}
        </span>
      </span>
    </button>
  );
};

export default ${componentName};
`;

  return {
    componentName,
    tsx,
    cssModule,
  };
}

/**
 * Generates a complete standalone ZIP bundle containing individual React TSX files,
 * CSS Modules, an index barrel file, token schemas, and documentation.
 */
export async function generateComponentBundleZip(
  components: AIButtonStudioComponent[],
  tokens: DesignTokens
): Promise<Blob> {
  const zip = new JSZip();

  // 1. Root Readme
  const readmeContent = `# AI Button Studio - Component Export Bundle

This package contains **${components.length} production-ready living buttons** generated by the AI Button Studio compiler.

## Contents
- \`src/components/\`: Individual React TSX components and paired CSS Modules (\`.module.css\`)
- \`src/components/index.ts\`: Barrel export file for drop-in usage
- \`src/tokens/designTokens.json\`: Studio design token configuration
- \`src/tokens/tokens.css\`: Global CSS custom properties
- \`package.json\`: Ready-to-install npm package manifest

## Included Components
${components
  .map((c, i) => `${i + 1}. **${toPascalCase(c.content.label || 'LivingButton')}** (\`${c.id}\`) - Action: \`${c.action.type}\` (${c.effects.base_style})`)
  .join('\n')}

## Installation & Quick Start

1. Install peer dependencies:
\`\`\`bash
npm install lucide-react clsx
\`\`\`

2. Import any component in your project:
\`\`\`tsx
import { ${components.map(c => toPascalCase(c.content.label || 'LivingButton')).slice(0, 3).join(', ')} } from './src/components';

export function Example() {
  return (
    <div className="flex gap-4 p-8">
      <${toPascalCase(components[0]?.content.label || 'LivingButton')}
        onClick={() => console.log('Clicked!')}
      />
    </div>
  );
}
\`\`\`

## Ethical Attribution & License Registry
${components
  .map(
    c =>
      `- **${c.content.label}**: Created by ${c.attribution.credit_owner} (${c.attribution.license_type} License)`
  )
  .join('\n')}
`;

  zip.file('README.md', readmeContent);

  // 2. package.json
  const packageJson = {
    name: 'ai-button-studio-bundle',
    version: '1.0.0',
    private: true,
    description: 'Exported living button components with CSS Modules and kinetic physics',
    main: 'src/components/index.ts',
    scripts: {
      build: 'tsc',
    },
    peerDependencies: {
      react: '^18.0.0 || ^19.0.0',
      'react-dom': '^18.0.0 || ^19.0.0',
      'lucide-react': '^0.400.0 || ^1.0.0',
    },
  };
  zip.file('package.json', JSON.stringify(packageJson, null, 2));

  // 3. Tokens Folder
  const tokensFolder = zip.folder('src/tokens')!;
  tokensFolder.file('designTokens.json', JSON.stringify(tokens, null, 2));

  const rootCssTokens = `/**
 * Global CSS Design Tokens
 * AI Button Studio
 */
:root {
  --primary-hue: ${tokens.primaryHue};
  --accent-color: ${tokens.accentColor};
  --btn-radius: ${tokens.borderRadius === 9999 ? '9999px' : `${tokens.borderRadius}px`};
  --border-thickness: ${tokens.borderThickness}px;
  --rgb-duration: ${tokens.rgbDuration}s;
  --shadow-intensity: ${tokens.shadowIntensity};
  --btn-transition-timing: ${tokens.transitionTiming};
}
`;
  tokensFolder.file('tokens.css', rootCssTokens);

  // 4. Components Folder
  const componentsFolder = zip.folder('src/components')!;
  const barrelExports: string[] = [];

  for (const comp of components) {
    const { componentName, tsx, cssModule } = generateReactWithCssModule(comp, tokens);
    componentsFolder.file(`${componentName}.tsx`, tsx);
    componentsFolder.file(`${componentName}.module.css`, cssModule);
    barrelExports.push(`export { default as ${componentName}, ${componentName} } from './${componentName}';`);
  }

  // 5. Index Barrel file
  const barrelContent = `/**
 * AI Button Studio - Component Bundle Barrel Export
 * Total Components: ${components.length}
 */

${barrelExports.join('\n')}
`;
  componentsFolder.file('index.ts', barrelContent);

  // 6. Generate Zip as Blob
  return await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: {
      level: 6,
    },
  });
}


