import { AIButtonStudioComponent, DesignTokens } from '../types';

/**
 * Generates automated header attribution watermark per Section 1.5
 */
function getAttributionHeader(attribution: AIButtonStudioComponent['attribution']): string {
  return `/**
 * ============================================================================
 * AI Button Studio - Auto-Credit & Ethical Attribution Registry
 * Author / Credit: ${attribution.credit_owner}
 * License: ${attribution.license_type}
 * Source Repository: ${attribution.source_repository || 'https://github.com/mutiagent-base/ai-button-studio-app-design'}
 * Generated by AI Button Studio Compiler
 * ============================================================================
 */\n\n`;
}

export function generateReactCode(component: AIButtonStudioComponent, tokens: DesignTokens): string {
  const isRGB = component.effects.special_features.includes('rgb_running_border');
  const isDynamicShadow = component.effects.special_features.includes('dynamic_shadow_cursor_tracking');

  return `${getAttributionHeader(component.attribution)}import React, { useState, useRef, useEffect } from 'react';
import { Sparkles, Rocket, Search, Plus, ArrowRight, Check, Loader2 } from 'lucide-react';

export interface LivingButtonProps {
  onClick?: () => void;
  disabled?: boolean;
  className?: string;
}

export const ${toPascalCase(component.content.label || 'LivingButton')}: React.FC<LivingButtonProps> = ({
  onClick,
  disabled = false,
  className = '',
}) => {
  const [state, setState] = useState<'idle' | 'hover' | 'loading' | 'success' | 'error'>('idle');
  const buttonRef = useRef<HTMLButtonElement>(null);

  ${isDynamicShadow ? `// 1. Dynamic Cursor Proximity Shadow Tracking (Section 3.3.A)
  useEffect(() => {
    const btn = buttonRef.current;
    if (!btn || disabled || state === 'loading') return;

    const handleMouseMove = (event: MouseEvent) => {
      const bounds = btn.getBoundingClientRect();
      const centerX = bounds.left + bounds.width / 2;
      const centerY = bounds.top + bounds.height / 2;

      const diffX = event.clientX - centerX;
      const diffY = event.clientY - centerY;

      // Dampen projection factor
      const shadowOffsetX = -(diffX / 16);
      const shadowOffsetY = -(diffY / 16);

      const distance = Math.sqrt(diffX * diffX + diffY * diffY);
      const blurRadius = Math.min(28, Math.max(8, 3500 / (distance + 1)));

      btn.style.boxShadow = \`\${shadowOffsetX.toFixed(1)}px \${shadowOffsetY.toFixed(1)}px \${blurRadius.toFixed(1)}px rgba(0, 0, 0, ${tokens.shadowIntensity})\`;
    };

    const handleMouseLeave = () => {
      btn.style.boxShadow = '';
    };

    window.addEventListener('mousemove', handleMouseMove);
    btn.addEventListener('mouseleave', handleMouseLeave);
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      btn.removeEventListener('mouseleave', handleMouseLeave);
    };
  }, [disabled, state]);` : ''}

  const handleClick = async (e: React.MouseEvent<HTMLButtonElement>) => {
    if (disabled || state === 'loading') return;
    setState('loading');

    try {
      if (onClick) await onClick();
      setState('success');
      setTimeout(() => setState('idle'), 1500);
    } catch {
      setState('error');
      setTimeout(() => setState('idle'), 1200);
    }
  };

  return (
    <button
      ref={buttonRef}
      id="${component.id}"
      type="button"
      tabIndex={${component.accessibility.tab_index}}
      aria-label="${component.accessibility.aria_label}"
      disabled={disabled || state === 'loading'}
      onClick={handleClick}
      onMouseEnter={() => setState('hover')}
      onMouseLeave={() => state !== 'loading' && state !== 'success' && setState('idle')}
      className={\`group relative inline-flex items-center justify-center gap-2.5 px-6 py-3 text-sm font-semibold tracking-wide transition-all duration-200 outline-none
        ${isRGB ? 'living-btn-rgb' : getBaseStyleClasses(component.effects.base_style)}
        \${state === 'loading' ? 'cursor-wait opacity-85' : 'cursor-pointer'}
        \${state === 'error' ? 'animate-shake !bg-rose-600 !text-white' : ''}
        \${state === 'success' ? 'animate-success-pop !bg-emerald-600 !text-white' : ''}
        \${disabled ? 'opacity-40 cursor-not-allowed filter grayscale' : 'hover:scale-[1.02] active:scale-[0.98]'}
        \${className}\`}
      style={{
        borderRadius: '${tokens.borderRadius === 9999 ? '9999px' : `${tokens.borderRadius}px`}',
        ['--btn-transition-timing' as any]: '${tokens.transitionTiming}',
        transitionTimingFunction: '${tokens.transitionTiming}',
      }}
    >
      {state === 'loading' ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin text-cyan-300" />
          <span>Processing...</span>
        </>
      ) : state === 'success' ? (
        <>
          <Check className="w-4 h-4 text-white" />
          <span>Completed</span>
        </>
      ) : (
        <>
          ${renderIconJSX(component.content.icon_name)}
          <span>${component.content.label}</span>
        </>
      )}
    </button>
  );
};
`;
}

export function generateHtmlCssCode(component: AIButtonStudioComponent, tokens: DesignTokens): string {
  const isRGB = component.effects.special_features.includes('rgb_running_border');
  const isDynamicShadow = component.effects.special_features.includes('dynamic_shadow_cursor_tracking');

  return `${getAttributionHeader(component.attribution)}<!-- HTML Button Markup -->
<button
  id="${component.id}"
  class="living-btn ${isRGB ? 'living-btn-rgb' : ''}"
  aria-label="${component.accessibility.aria_label}"
  tabindex="${component.accessibility.tab_index}"
>
  <span class="btn-content">
    <span class="btn-label">${component.content.label}</span>
  </span>
</button>

<style>
:root {
  --btn-radius: ${tokens.borderRadius === 9999 ? '9999px' : `${tokens.borderRadius}px`};
  --border-thickness: ${tokens.borderThickness}px;
  --rgb-duration: ${tokens.rgbDuration}s;
  --shadow-intensity: ${tokens.shadowIntensity};
  --btn-transition-timing: ${tokens.transitionTiming};
}

.living-btn {
  position: relative;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 12px 24px;
  font-family: system-ui, sans-serif;
  font-size: 14px;
  font-weight: 600;
  color: #ffffff;
  background: #0f172a;
  border-radius: var(--btn-radius);
  border: 1px solid rgba(255, 255, 255, 0.15);
  cursor: pointer;
  outline: none;
  transition: all 0.25s var(--btn-transition-timing, cubic-bezier(0.4, 0, 0.2, 1));
}

${isRGB ? `/* RGB Conic Gradient Implementation */
.living-btn-rgb {
  border: none;
  overflow: hidden;
  z-index: 1;
}

.living-btn-rgb::before {
  content: '';
  position: absolute;
  top: -50%;
  left: -50%;
  width: 200%;
  height: 200%;
  background: conic-gradient(#ff0055, #fe9000, #fff020, #3edf4b, #3363ff, #b102b7, #ff0055);
  animation: rotate-border var(--rgb-duration) linear infinite;
  z-index: -2;
  transition: animation-duration 0.3s ease;
}

.living-btn-rgb::after {
  content: '';
  position: absolute;
  inset: var(--border-thickness);
  background: #111827;
  border-radius: calc(var(--btn-radius) - var(--border-thickness));
  z-index: -1;
}

.living-btn-rgb:hover {
  --rgb-duration: 0.8s;
}

.living-btn-rgb:active {
  filter: brightness(1.3);
}

@keyframes rotate-border {
  100% { transform: rotate(360deg); }
}` : ''}
</style>

${isDynamicShadow ? `<script>
// Dynamic Cursor Tracking Shadow (Section 3.3.A)
const btn = document.getElementById('${component.id}');
if (btn) {
  document.addEventListener('mousemove', (event) => {
    const bounds = btn.getBoundingClientRect();
    const centerX = bounds.left + bounds.width / 2;
    const centerY = bounds.top + bounds.height / 2;

    const diffX = event.clientX - centerX;
    const diffY = event.clientY - centerY;

    const shadowOffsetX = -(diffX / 15);
    const shadowOffsetY = -(diffY / 15);
    const distance = Math.sqrt(diffX * diffX + diffY * diffY);
    const blurRadius = Math.min(30, Math.max(10, 4000 / distance));

    btn.style.boxShadow = \`\${shadowOffsetX}px \${shadowOffsetY}px \${blurRadius}px rgba(0, 0, 0, ${tokens.shadowIntensity})\`;
  });
}
</script>` : ''}
`;
}

export function generateVueCode(component: AIButtonStudioComponent, tokens: DesignTokens): string {
  return `${getAttributionHeader(component.attribution)}<template>
  <button
    id="${component.id}"
    :class="[
      'living-btn',
      '${component.effects.special_features.includes('rgb_running_border') ? 'living-btn-rgb' : ''}',
      { 'is-loading': loading }
    ]"
    :aria-label="'${component.accessibility.aria_label}'"
    :tabindex="${component.accessibility.tab_index}"
    @click="handleClick"
  >
    <span v-if="loading">Processing...</span>
    <span v-else>${component.content.label}</span>
  </button>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const loading = ref(false);

const emit = defineEmits(['click']);

const handleClick = async () => {
  if (loading.value) return;
  loading.value = true;
  emit('click');
  setTimeout(() => { loading.value = false; }, 1200);
};
</script>

<style scoped>
.living-btn {
  padding: 12px 24px;
  border-radius: ${tokens.borderRadius === 9999 ? '9999px' : `${tokens.borderRadius}px`};
  background: #0f172a;
  color: #ffffff;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.25s ${tokens.transitionTiming};
}
</style>
`;
}

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('') || 'LivingButton';
}

function getBaseStyleClasses(style: string): string {
  switch (style) {
    case 'neon_blue_glow':
      return 'bg-cyan-950/80 text-cyan-200 border border-cyan-500/50 shadow-[0_0_20px_rgba(6,182,212,0.3)] hover:shadow-[0_0_30px_rgba(6,182,212,0.55)] hover:border-cyan-400';
    case 'gradient_fill':
      return 'bg-gradient-to-r from-sky-500 via-indigo-500 to-purple-600 text-white shadow-lg shadow-indigo-500/25 hover:shadow-indigo-500/45';
    case 'outline_rgb':
      return 'bg-neutral-900/90 text-white border border-neutral-700';
    case 'soft_shadow':
      return 'bg-neutral-800 text-neutral-100 border border-neutral-700/60 shadow-md shadow-black/40 hover:bg-neutral-750';
    default:
      return 'bg-sky-600 text-white shadow-md hover:bg-sky-500';
  }
}

function renderIconJSX(iconName?: string): string {
  switch (iconName) {
    case 'rocket': return '<Rocket className="w-4 h-4 text-cyan-300 group-hover:translate-x-0.5 transition-transform" />';
    case 'sparkles': return '<Sparkles className="w-4 h-4 text-amber-300 group-hover:rotate-12 transition-transform" />';
    case 'search': return '<Search className="w-4 h-4 text-neutral-300" />';
    case 'plus': return '<Plus className="w-4 h-4 text-white group-hover:rotate-90 transition-transform" />';
    case 'arrow-right': return '<ArrowRight className="w-4 h-4 text-cyan-400 group-hover:translate-x-1 transition-transform" />';
    case 'check': return '<Check className="w-4 h-4 text-emerald-400" />';
    default: return '<Sparkles className="w-4 h-4 text-cyan-300" />';
  }
}
